image: archlinux
packages:
  - devtools
  - python-srcinfo
  - rsync
sources:
  - https://aur.archlinux.org/aurutils
secrets:
  - 6654bcbe-8af2-4ad1-adc0-2a042b6dcd69
  - 780c04c7-422e-4e78-ae8f-e80d837c4ea6
tasks:
  - setup: |
      export GPGKEY=F9CC7EE42BB006F991273094E20AEF8049CC3757
      sudo pacman-key --recv-keys F9CC7EE42BB006F991273094E20AEF8049CC3757
      sudo pacman-key --lsign-key F9CC7EE42BB006F991273094E20AEF8049CC3757

      mkdir -p ~/.gnupg
      echo "keyserver-options auto-key-retrieve" > ~/.gnupg/gpg.conf
      gpg --recv-keys DBE7D3DD8C81D58D0A13D0E76BC26A17B9B7018A
      echo "th73.ovh ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIEqCtC2LuwcWztCNr96VzrG5TJ2yJSSMVnQ+yKqB95CZ" > ~/.ssh/known_hosts

      cd aurutils
      makepkg -si --noprogressbar --noconfirm
      cd ..

      mkdir -p local
      REPO_URL="https://archmirror.th73.ovh/sr.ht/sr.ht.db.sig"
      if curl --output /dev/null --silent --head --fail "$REPO_URL"; then
          scp archmirror@th73.ovh:http/sr.ht/sr.ht.db.tar.gz local/localrepo.db.tar.gz
          scp archmirror@th73.ovh:http/sr.ht/sr.ht.db.tar.gz.sig local/localrepo.db.tar.gz.sig
          scp archmirror@th73.ovh:http/sr.ht/sr.ht.files.tar.gz local/localrepo.files.tar.gz
          scp archmirror@th73.ovh:http/sr.ht/sr.ht.files.tar.gz.sig local/localrepo.files.tar.gz.sig
          ln -s localrepo.db.tar.gz local/localrepo.db
          ln -s localrepo.files.tar.gz local/localrepo.files
          ln -s localrepo.db.tar.gz.sig local/localrepo.db.sig
          ln -s localrepo.files.tar.gz.sig local/localrepo.files.sig

          cat << EOF | sudo tee -a /etc/pacman.conf
      [sr.ht]
      SigLevel = Required TrustedOnly
      Server = https://archmirror.th73.ovh/sr.ht/
      EOF
      else
          repo-add -s local/localrepo.db.tar.gz
      fi

      # TODO: use repositories feature of build.sr.ht once setting a siglevel is
      # supported
      cat << EOF | sudo tee -a /etc/pacman.conf
      [localrepo]
      SigLevel = Required TrustedOnly
      Server = file:///home/build/local
      EOF
      sudo pacman -Sy --noprogressbar
  - build: |
      cd pkgbuilds
      ./build.sh
  - upload: |
      cd local/
      mv localrepo.files sr.ht.files
      mv localrepo.files.sig sr.ht.files.sig
      mv localrepo.files.tar.gz sr.ht.files.tar.gz
      mv localrepo.files.tar.gz.sig sr.ht.files.tar.gz.sig
      mv localrepo.db sr.ht.db
      mv localrepo.db.sig sr.ht.db.sig
      mv localrepo.db.tar.gz sr.ht.db.tar.gz
      mv localrepo.db.tar.gz.sig sr.ht.db.tar.gz.sig
      cd ..

      rsync -av local/ archmirror@th73.ovh:http/sr.ht
