image: archlinux
packages:
  - devtools
  - python-srcinfo
  - rsync
sources:
  - https://aur.archlinux.org/aurutils
secrets:
  - 6654bcbe-8af2-4ad1-adc0-2a042b6dcd69
  - 780c04c7-422e-4e78-ae8f-e80d837c4ea6
tasks:
  - setup: |
      export GPGKEY=F9CC7EE42BB006F991273094E20AEF8049CC3757
      sudo pacman-key --recv-keys F9CC7EE42BB006F991273094E20AEF8049CC3757
      sudo pacman-key --lsign-key F9CC7EE42BB006F991273094E20AEF8049CC3757

      mkdir -p ~/.gnupg
      echo "keyserver-options auto-key-retrieve" > ~/.gnupg/gpg.conf
      gpg --recv-keys DBE7D3DD8C81D58D0A13D0E76BC26A17B9B7018A
      echo "th73.ovh ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIEqCtC2LuwcWztCNr96VzrG5TJ2yJSSMVnQ+yKqB95CZ" > ~/.ssh/known_hosts

      cd aurutils
      makepkg -si --noprogressbar --noconfirm
      cd ..

      mkdir -p /home/build/local
      scp archmirror@th73.ovh:http/sr.ht/sr.ht.db.tar.gz /home/build/local/localrepo.db.tar.gz
      scp archmirror@th73.ovh:http/sr.ht/sr.ht.db.tar.gz.sig /home/build/local/localrepo.db.tar.gz.sig
      scp archmirror@th73.ovh:http/sr.ht/sr.ht.files.tar.gz /home/build/local/localrepo.files.tar.gz
      scp archmirror@th73.ovh:http/sr.ht/sr.ht.files.tar.gz.sig /home/build/local/localrepo.files.tar.gz.sig
      ln -s localrepo.db.tar.gz local/localrepo.db
      ln -s localrepo.files.tar.gz local/localrepo.files
      #repo-add /home/build/local/localrepo.db.tar

      cat << EOF | sudo tee -a /etc/pacman.conf
      [localrepo]
      SigLevel = Optional TrustAll
      Server = file:///home/build/local

      [sr.ht]
      SigLevel = Required TrustedOnly
      Server = https://archmirror.th73.ovh/sr.ht/
      EOF
      sudo pacman -Sy --noprogressbar
  - build: |
      cd pkgbuilds
      ./build.sh
  - upload: |
      rsync -av --ignore-missing-args local/*.pkg.tar* archmirror@th73.ovh:http/sr.ht
      scp local/localrepo.files.tar.gz archmirror@th73.ovh:http/sr.ht/sr.ht.files.tar.gz
      scp local/localrepo.files.tar.gz.sig archmirror@th73.ovh:http/sr.ht/sr.ht.files.tar.gz.sig
      scp local/localrepo.db.tar.gz archmirror@th73.ovh:http/sr.ht/sr.ht.db.tar.gz
      scp local/localrepo.db.tar.gz.sig archmirror@th73.ovh:http/sr.ht/sr.ht.db.tar.gz.sig
      #ssh archmirror@th73.ovh "repo-add -p http/sr.ht/sr.ht.db.tar.gz http/sr.ht/*.pkg.tar.xz"
